name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 12 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been inactive for quite awhile :('
        stale-pr-message: 'This PR has been inactive and has been marked as stale. :('
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
